# Generated by Django 3.0.5 on 2020-06-05 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desktop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('condition', models.CharField(choices=[('available', 'available'), ('comingsoon', 'comingsoon'), ('sold', 'sold')], default='available', max_length=20)),
                ('issues', models.CharField(default='good', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('condition', models.CharField(choices=[('available', 'available'), ('comingsoon', 'comingsoon'), ('sold', 'sold')], default='available', max_length=20)),
                ('issues', models.CharField(default='good', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('condition', models.CharField(choices=[('available', 'available'), ('comingsoon', 'comingsoon'), ('sold', 'sold')], default='available', max_length=20)),
                ('issues', models.CharField(default='good', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
